### PR TITLE
Add hook for dev testing.

### PR DESCRIPTION
**Pull request by phbcanada**
Also it's convenient for developers to have access to a display name for the current api.

### CODE REVIEW

**Comment by phbcanada** [comment]
@gregra81 - if this is ok with you guys, please merge.

**Comment by phbcanada** [comment]
@gregra81 - please merge if you guys are ok with this now. thanks

**Comment by gregra81** [comment]
@phbcanada - Regarding indentations, we are working with tabs, not spaces. @watanas can you confirm?

**Comment by phbcanada** [comment]
Most of the existing code uses spaces. This is our internal standard.

**Comment by watanas** [comment]
@gregra81 I thought we were using tabs. The google javascript guidelines say to use the C++ formatting rules "in spirit", which says, "We use spaces for indentation. Do not use tabs in your code."
https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Spaces_vs._Tabs

**Comment by watanas** [comment]
@gregra81 @phbcanada Oops "tabs" -> "spaces".

**Comment by gregra81** [comment]
OK, so let's standardize on spaces (this requires major refractor of our current code)

**Comment by gregra81** [comment]
BTW, let's agree on the specifics once and for all to avoid future major code refractor. In webstorm I set these preferences and then align everything automatically:
screen shot 2015-07-15 at 9 07 07 pm

Is it OK?

**Comment by watanas** [comment]
Those match my settings.

**Comment by gregra81** [comment]
Great, sharing these settings with our team in Tel Aviv
@yardenr, @einat-bar, @rozman1234

**Comment by gregra81** [comment]
@phbcanada, Now, after Steven has refactored the files (by changing tabs to spaces), this pull request can't be automatically merged. Can you do another pull request with the updated code?

@watanas

**Pull request closed without merging**
