### PR TITLE
watanas fixes

### PR DESCRIPTION
**Pull request by watanas**

### CODE REVIEW

**Comment by watanas** [comment]
Please review and merge if okay. Thanks!

**Comment by gregra81** [comment]
@watanas, shouldn't we bump up SDK version and update CHANGELOG.md?

**Comment by watanas** [comment]
When there's to be a new release, then yes, I think those should be done.

**Comment by gregra81** [comment]
Isn't it a new release right now - as soon as I merge that pull request and upload, it will be a new version of the code. Or am I missing something?

**Comment by watanas** [comment]
Well, yes, when you upload it. But Paul had pushed a couple of changes to master last month, and AFAIK there was no new release for those changes. So I would expect you'd merge the pull request (if it's okay) then update the changelog (for all of the changes that will be included) and bump the version, then upload.

**Comment by gregra81** [comment]
I suggest that whoever makes changes should also update the changelog and bump up the version, all in his pull request. Then, after the merge all that will be left is to upload the new SDK.
WDYT?

**Comment by watanas** [comment]
Since the release is a manual process, I don't think the version number should be bumped for every pull request (unless you intend to release for every pull request, which IIUC is not the case) - I think the version number should be bumped by the person who is doing the release, when they do the release.
I'll update the changelog with my changes and Paul's relevant changes.

**Comment by watanas** [comment]
@gregra81 changelog updated

**Pull request merged**
